name: '${name}'
version: '${version}'
main: '${main}'
folia-supported: true
authors: [ Drak ]

commands:
  entity-count:
    description: Get the count of entities in the server.
    aliases:
      - entityc
      - counte
      - countentities
    permission: bou.command.entity-count
  boumessage:
    description: Send a message to a user.
    aliases:
      - boumsg
    permission: bou.command.boumessage
  boutitle:
    description: Send a title to a user.
    aliases:
      - bout
    permission: bou.command.boutitle